/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDelegationRegistry } from "./IDelegationRegistry";
export type { MockMoonbirds } from "./MockMoonbirds";
export type { Toobins } from "./Toobins";
